/*** STATUS CODES ***/
#define STATUS_OK 0
#define STATUS_WARN 1
#define STATUS_ERROR 2
#define STATUS_STALE 3

#define CODE_OK 0
#define CODE_NO_RESPONSE 1
#define CODE_REQUEST_FAILED 2
#define CODE_UNKNOWN_ERROR 3

#define ATLAS_EC_MIN_UPDATE_INTERVAL 3000
#define WATER_LEVEL_UPDATE_INTERVAL 50
#define AM2315_UPDATE_INTERVAL 1000

#define BAUD_RATE 115200

#define LIGHT_ON    LOW
#define LIGHT_OFF   HIGH

